// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3EEdl0dhUqU12lZqdb-XoPL-kB2l-efo',
    appId: '1:795079627606:web:644c12703fd780b2c13cf7',
    messagingSenderId: '795079627606',
    projectId: 'frutifruti',
    authDomain: 'frutifruti.firebaseapp.com',
    storageBucket: 'frutifruti.firebasestorage.app',
    measurementId: 'G-40BTSNKF68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9HxEnIwMmDuwEoE5h_6zVaBx47_5yiYE',
    appId: '1:795079627606:android:acdecb56734a13ecc13cf7',
    messagingSenderId: '795079627606',
    projectId: 'frutifruti',
    storageBucket: 'frutifruti.firebasestorage.app',
  );
}
